version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: golovanovya/php-fpm:latest
    volumes:
      - ./:/var/www
    working_dir:
      /var/www