version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: golovanovya/php-fpm:latest
    volumes:
      - ./:/var/www
    working_dir:
      /var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: finbridge